### ISSUE TITLE
Is there a repository where I can directly use this component?

### ISSUE THREAD

**Issue by tauroamp** [shaneharris/aframe-material-collection#1]
Hi!
I am trying to use this component using npm, but it generates errors. My operating system is Ubuntu v18 with node v8.10.0 and npm v3.5.2

But what really interests me is whether there is a version (rawgit, cdn) that can be used directly without having to use npm?
I've been searching and I can not find any, like most AFrame components.
Thank you in advance!

**Comment by sidequestlegend** [comment]
Hi There! Apologies for the delayed response! I will do a release on github soon but would you also like it published on a cdn too?

Ill build the dist files a bit more often too so you can grab the build from rawgit.

**Comment by sidequestlegend** [comment]
OK I have added the dist files to the repo to link via rawgit i.e 
`https://cdn.rawgit.com/shaneharris/aframe-material-collection/master/dist/aframe-material-collection.min.js`
