### ISSUE TITLE
add Tabs 

### ISSUE THREAD

**Issue by arpu** [shaneharris/aframe-material-collection#2]
would it be possible to add some tab function?

**Comment by sidequestlegend** [comment]
I have a use case for this too so ill implement in the next day or so!

**Comment by sidequestlegend** [comment]
I have added a method to update the scroll pane content dymanically and trigger the re-render of that content. I will add an example soon that leverages this to provide tabs capability

**Comment by sidequestlegend** [comment]
I still haven't implemented this yet. Ive got one or two other things on my list first but i will circle back to this.

**Comment by arpu** [comment]
closing this in favor for this example https://codesandbox.io/s/vv6jm1l06l
