### ISSUE TITLE
Add a window component

### ISSUE THREAD

**Issue by tlaukkan** [shaneharris/aframe-material-collection#5]
It would be nice to have a window component like the one in Shane's Editor providing title bar, close button and scroll pane.

**Comment by sidequestlegend** [comment]
I wonder if the modal component already achieves this? You can include separate parts of the UI kit if you dont want to use all of it but the modal component will open a separate window, with a title, scroll pane and close button. It can be positioned anywhere yoou like and has a built in scale animation for opening/closing

 does this do what you need?

**Comment by tlaukkan** [comment]
Yes, thank you. I think the documentation is yet to cover the modal component.

**Comment by sidequestlegend** [comment]
yep your right! i need to catch up there! ive just been adding stuff as and when i need it. ill close this then if you are happy enough. feel free to open another if you have any problems.
